os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - main
    - master
    - develop

before_install:
  - env | sort
  - export EXPORT_TESTS_RESULTS=true

install:
  # Execute CI build hooks
  - ./hooks/run build "${VARIANT}" "${BASE}"

before_script:
  # Display docker images
  - docker images
  # Codacy Coverage Reporter
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download

script:
  # Execute CI test hooks
  - ./hooks/run test "${VARIANT}" "${BASE}"

after_success:
  # Codacy Coverage Reporter
  - test -z "${CODACY_PROJECT_TOKEN}" || bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./coverage/coverage-phpunit-cobertura.xml

notifications:
  email: false

matrix:
  allow_failures:
    - env: VARIANT=debian BASE=fpm

env: # Environments
    - VARIANT=alpine BASE=fpm
    - VARIANT=debian BASE=fpm
    #- VARIANT=fpm-alpine BASE=fpm
    #- VARIANT=fpm BASE=fpm
    #- VARIANT=apache BASE=apache
